/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Carlos Eduardo
 */
public class TelaCadastroVeiculo extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastrarVeiculo
     */
    public TelaCadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoTitulo = new javax.swing.JLabel();
        textoModeloCarro = new javax.swing.JLabel();
        textoAnoCarro = new javax.swing.JLabel();
        textoPlacaCarro = new javax.swing.JLabel();
        textoCombustivelCarro = new javax.swing.JLabel();
        textoMedKmLCarro = new javax.swing.JLabel();
        textoCodigoEmpresaCarro = new javax.swing.JLabel();
        campoAnoCarro = new javax.swing.JTextField();
        campoPlacaCarro = new javax.swing.JTextField();
        campoCombusitvelCarro = new javax.swing.JTextField();
        campoCodigoEmpresa = new javax.swing.JTextField();
        campoMedKmLCarro = new javax.swing.JTextField();
        campoModeloCarro = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        textoTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textoTitulo.setText("Cadastro de Veículos da Empresa");

        textoModeloCarro.setText("Modelo:");

        textoAnoCarro.setText("Ano:");

        textoPlacaCarro.setText("Placa:");

        textoCombustivelCarro.setText("Combustível:");

        textoMedKmLCarro.setText("Média Km por Litro:");

        textoCodigoEmpresaCarro.setText("Código da Empresa:");

        campoAnoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoCarroActionPerformed(evt);
            }
        });

        campoCombusitvelCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCombusitvelCarroActionPerformed(evt);
            }
        });

        campoCodigoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoEmpresaActionPerformed(evt);
            }
        });

        campoMedKmLCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMedKmLCarroActionPerformed(evt);
            }
        });

        campoModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModeloCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTitulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoCodigoEmpresaCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoMedKmLCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMedKmLCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCombustivelCarro)
                                    .addComponent(textoPlacaCarro)
                                    .addComponent(textoAnoCarro)
                                    .addComponent(textoModeloCarro))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoAnoCarro)
                                        .addComponent(campoCombusitvelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(textoTitulo)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoModeloCarro)
                    .addComponent(campoModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoAnoCarro)
                    .addComponent(campoAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPlacaCarro)
                    .addComponent(campoPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCombustivelCarro)
                    .addComponent(campoCombusitvelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMedKmLCarro)
                    .addComponent(campoMedKmLCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigoEmpresaCarro)
                    .addComponent(campoCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoAnoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoCarroActionPerformed

    private void campoCombusitvelCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCombusitvelCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCombusitvelCarroActionPerformed

    private void campoCodigoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoEmpresaActionPerformed

    private void campoMedKmLCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMedKmLCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMedKmLCarroActionPerformed

    private void campoModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModeloCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAnoCarro;
    private javax.swing.JTextField campoCodigoEmpresa;
    private javax.swing.JTextField campoCombusitvelCarro;
    private javax.swing.JTextField campoMedKmLCarro;
    private javax.swing.JTextField campoModeloCarro;
    private javax.swing.JTextField campoPlacaCarro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoAnoCarro;
    private javax.swing.JLabel textoCodigoEmpresaCarro;
    private javax.swing.JLabel textoCombustivelCarro;
    private javax.swing.JLabel textoMedKmLCarro;
    private javax.swing.JLabel textoModeloCarro;
    private javax.swing.JLabel textoPlacaCarro;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
