/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import Model.Viagem;
import controller.ControllerRelatorios;

import org.jfree.chart.*;

/**
 *
 * @author Carlos Eduardo
 */
public class TelaRelatorio extends javax.swing.JPanel {

    private ControllerRelatorios controller;

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        this.controller = new ControllerRelatorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoEmpresaRelatorio = new javax.swing.JLabel();
        textoPaisRelatorio = new javax.swing.JLabel();
        textoDataInicialRelatorio = new javax.swing.JLabel();
        textoDataFinalRelatorio = new javax.swing.JLabel();
        campoDataInicialRelatorio = new javax.swing.JTextField();
        campoPaisRelatorio = new javax.swing.JTextField();
        campoEmpresaRelatorio = new javax.swing.JTextField();
        campoDataFinalRelatorio = new javax.swing.JTextField();
        painelGraficosRelatorios = new javax.swing.JPanel();
        btnLimparRelatorios = new javax.swing.JButton();
        btnMostrarRelatorios = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoEmpresaRelatorio.setText("Empresa:");

        textoPaisRelatorio.setText("País:");

        textoDataInicialRelatorio.setText("Data de Início:");

        textoDataFinalRelatorio.setText("Data Final:");

        painelGraficosRelatorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout painelGraficosRelatoriosLayout = new javax.swing.GroupLayout(painelGraficosRelatorios);
        painelGraficosRelatorios.setLayout(painelGraficosRelatoriosLayout);
        painelGraficosRelatoriosLayout.setHorizontalGroup(
            painelGraficosRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        painelGraficosRelatoriosLayout.setVerticalGroup(
            painelGraficosRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        btnLimparRelatorios.setText("Limpar");
        btnLimparRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparRelatoriosActionPerformed(evt);
            }
        });

        btnMostrarRelatorios.setText("Mostrar");
        btnMostrarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelGraficosRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoDataInicialRelatorio)
                            .addComponent(textoPaisRelatorio)
                            .addComponent(textoEmpresaRelatorio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDataInicialRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPaisRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEmpresaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textoDataFinalRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDataFinalRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarRelatorios)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparRelatorios)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmpresaRelatorio)
                    .addComponent(campoEmpresaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPaisRelatorio)
                    .addComponent(campoPaisRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDataInicialRelatorio)
                    .addComponent(textoDataFinalRelatorio)
                    .addComponent(campoDataInicialRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataFinalRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparRelatorios)
                    .addComponent(btnMostrarRelatorios))
                .addGap(18, 18, 18)
                .addComponent(painelGraficosRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparRelatoriosActionPerformed
        campoDataFinalRelatorio.setText("");
        campoDataInicialRelatorio.setText("");
        campoEmpresaRelatorio.setText("");
        campoPaisRelatorio.setText("");
        painelGraficosRelatorios.removeAll();
    }//GEN-LAST:event_btnLimparRelatoriosActionPerformed

    private void btnMostrarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRelatoriosActionPerformed
        String empresaRelatorio = campoEmpresaRelatorio.getText();
        String paisRelatorio = campoPaisRelatorio.getText();
        Date inicialRelatorio = null;
        Date finalRelatorio = null;

        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        try {
            finalRelatorio = formatador.parse(campoDataFinalRelatorio.getText());
            inicialRelatorio = formatador.parse(campoDataInicialRelatorio.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastroEmpresa.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
        }

        List<Viagem> viagens = this.controller.dadosRelatorios(inicialRelatorio, finalRelatorio);

        for ( Viagem viagem : viagens ){
            System.out.println(viagem.getCo2Emitido());
        }


    }//GEN-LAST:event_btnMostrarRelatoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparRelatorios;
    private javax.swing.JButton btnMostrarRelatorios;
    private javax.swing.JTextField campoDataFinalRelatorio;
    private javax.swing.JTextField campoDataInicialRelatorio;
    private javax.swing.JTextField campoEmpresaRelatorio;
    private javax.swing.JTextField campoPaisRelatorio;
    private javax.swing.JPanel painelGraficosRelatorios;
    private javax.swing.JLabel textoDataFinalRelatorio;
    private javax.swing.JLabel textoDataInicialRelatorio;
    private javax.swing.JLabel textoEmpresaRelatorio;
    private javax.swing.JLabel textoPaisRelatorio;
    // End of variables declaration//GEN-END:variables
}
